# Generated by Django 5.2.17 on 2026-09-19 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('owner_name', models.CharField(max_length=120)),
                ('owner_phone', models.CharField(max_length=30)),
                ('owner_email', models.EmailField(blank=True, max_length=254)),
                ('area', models.CharField(help_text='Town/area, e.g. Malindi Town', max_length=100)),
                ('estate', models.CharField(blank=True, max_length=100)),
                ('house_type', models.CharField(choices=[('Single room', 'Single room'), ('Bedsitter', 'Bedsitter'), ('Studio', 'Studio'), ('One bedroom', 'One bedroom'), ('Two bedroom', 'Two bedroom'), ('Three bedroom', 'Three bedroom'), ('Shared accommodation', 'Shared accommodation'), ('Other', 'Other')], max_length=40)),
                ('rent', models.PositiveIntegerField(verbose_name='Monthly rent (KSh)')),
                ('deposit', models.PositiveIntegerField(default=0, verbose_name='Deposit (KSh)')),
                ('units_total', models.PositiveIntegerField(default=1)),
                ('units_vacant', models.PositiveIntegerField(default=1)),
                ('description', models.TextField()),
                ('environment', models.TextField(blank=True, help_text='Neighbourhood, shops, transport, noise', verbose_name='Around the house')),
                ('wifi', models.BooleanField(default=False, verbose_name='Wi-Fi')),
                ('water', models.BooleanField(default=False, verbose_name='Reliable water')),
                ('electricity', models.BooleanField(default=True)),
                ('parking', models.BooleanField(default=False)),
                ('security', models.BooleanField(default=False, verbose_name='Security guard')),
                ('cctv', models.BooleanField(default=False, verbose_name='CCTV')),
                ('furnished', models.BooleanField(default=False)),
                ('own_compound', models.BooleanField(default=False)),
                ('balcony', models.BooleanField(default=False)),
                ('kitchen', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('verification', models.CharField(choices=[('landlord', 'Landlord listed'), ('pending', 'Pending verification'), ('verified', 'AMOX Verified'), ('partner', 'Partner property')], default='landlord', max_length=10)),
                ('verified_on', models.DateField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('views', models.PositiveIntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'properties',
                'ordering': ['-featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Contact name')),
                ('business', models.CharField(max_length=140)),
                ('category', models.CharField(choices=[('internet', 'Internet/Wi-Fi'), ('gas', 'Gas'), ('items', 'Mattress & household items'), ('moving', 'Moving'), ('other', 'Other')], max_length=10)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('coverage', models.CharField(blank=True, max_length=200)),
                ('details', models.TextField(blank=True, verbose_name='Packages, prices, notes')),
                ('commission_pct', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('suspended', 'Suspended')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('house', 'House request'), ('inquiry', 'Property inquiry'), ('internet', 'Internet'), ('gas', 'Gas cylinder'), ('items', 'Mattress / household'), ('moving', 'Relocation'), ('other', 'Other service'), ('general', 'General enquiry')], max_length=10)),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=30)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('suggested', 'House suggested'), ('viewing', 'Viewing arranged'), ('connected', 'Connected'), ('completed', 'Completed'), ('closed', 'Closed')], default='new', max_length=10)),
                ('notes', models.TextField(blank=True, help_text='Internal notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.property')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], default='photo', max_length=5)),
                ('section', models.CharField(choices=[('inside', 'Inside the house'), ('around', 'Around the house')], default='inside', max_length=6)),
                ('file', models.FileField(upload_to='properties/%Y/%m/')),
                ('thumb', models.ImageField(blank=True, editable=False, upload_to='thumbs/%Y/%m/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='core.property')),
            ],
        ),
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km', models.DecimalField(decimal_places=1, max_digits=5)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.institution')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distances', to='core.property')),
            ],
            options={
                'ordering': ['km'],
                'unique_together': {('property', 'institution')},
            },
        ),
    ]
