# Generated by Django 5.2.17 on 2026-10-03 04:10

from django.db import migrations, models


INSTITUTIONS = [("MKU Malindi", "mku-malindi"), ("KMTC Malindi", "kmtc-malindi"), ("Pwani University", "pwani-university"),
                ("Malindi Sub-County Hospital", "malindi-sub-county-hospital"), ("KMTC Kilifi", "kmtc-kilifi"),
                ("KMTC Msambweni", "kmtc-msambweni"), ("KMTC Mombasa", "kmtc-mombasa"), ("Port Reitz Hospital", "port-reitz-hospital"),
                ("North Coast Medical Training College", "north-coast-mtc")]

def add_institutions(apps, schema_editor):
    Inst = apps.get_model("core", "Institution")
    for name, slug in INSTITUTIONS:
        Inst.objects.get_or_create(slug=slug, defaults={"name": name})


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='laundry',
            field=models.BooleanField(default=False, verbose_name='Laundry area'),
        ),
        migrations.AddField(
            model_name='property',
            name='nearby_hospitals',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Nearby hospitals / clinics'),
        ),
        migrations.AddField(
            model_name='property',
            name='nearby_institutions',
            field=models.CharField(blank=True, default='', help_text='e.g. MKU Malindi, Malindi High School', max_length=200, verbose_name='Nearby schools / colleges'),
        ),
        migrations.AddField(
            model_name='property',
            name='nearby_landmarks',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Other landmarks'),
        ),
        migrations.AddField(
            model_name='property',
            name='nearby_shops',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Nearby shops / markets'),
        ),
        migrations.AddField(
            model_name='property',
            name='nearby_transport',
            field=models.CharField(blank=True, default='', help_text='e.g. Matatu stage 300 m, tarmac road', max_length=200, verbose_name='Transport and roads'),
        ),
        migrations.AddField(
            model_name='property',
            name='pet_friendly',
            field=models.BooleanField(default=False, verbose_name='Pet-friendly'),
        ),
        migrations.AddField(
            model_name='property',
            name='shared_compound',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='install_fee',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Installation fee'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='package',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Package name'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='price',
            field=models.CharField(blank=True, default='', help_text='e.g. KSh 2,500/month', max_length=60, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='speed',
            field=models.CharField(blank=True, default='', help_text='e.g. 10 Mbps', max_length=40),
        ),
        migrations.RunPython(add_institutions, migrations.RunPython.noop),
    ]
