# Generated by Django 5.2.17 on 2026-10-05 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_phase1_finish'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='ac',
            field=models.BooleanField(default=False, verbose_name='Air conditioning'),
        ),
        migrations.AddField(
            model_name='property',
            name='ceiling',
            field=models.BooleanField(default=False, verbose_name='Ceiling'),
        ),
        migrations.AddField(
            model_name='property',
            name='fans',
            field=models.BooleanField(default=False, verbose_name='Fans'),
        ),
        migrations.AddField(
            model_name='property',
            name='tiles',
            field=models.BooleanField(default=False, verbose_name='Tiles'),
        ),
        migrations.AddField(
            model_name='property',
            name='wardrobe',
            field=models.BooleanField(default=False, verbose_name='Wardrobe'),
        ),
    ]
