# Generated by Django 5.2.17 on 2026-09-26 08:59

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_more_amenities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=140)),
                ('link', models.CharField(blank=True, help_text='A page like /houses/ or a full web address', max_length=200, validators=[core.models.validate_link], verbose_name='Link (optional)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Show on website')),
                ('expires_on', models.DateField(blank=True, null=True, verbose_name='Hide after')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
