from django.urls import path
from . import views as v, console as c
from django.views.generic import RedirectView
urlpatterns = [
    path("", v.home, name="home"),
    path("houses/", v.property_list, name="houses"),
    path("houses/near/<slug:institution>/", v.property_list, name="houses_near"),
    path("houses/<slug:slug>/", v.property_detail, name="property_detail"),
    path("services/", v.services, name="services"),
    path("request/<slug:kind>/", v.request_service, name="request"),
    path("landlords/", v.landlords, name="landlords"),
    path("landlords/list/", v.list_property, name="list_property"),
    path("providers/", v.providers, name="providers"),
    path("about/", v.about, name="about"),
    path("contact/", v.contact, name="contact"),
    path("thanks/", v.thanks, name="thanks"),
    path("privacy/", v.legal, {"page": "privacy"}, name="privacy"),
    path("terms/", v.legal, {"page": "terms"}, name="terms"),
    path("dashboard/", RedirectView.as_view(pattern_name="console")),
    path("console/", c.home, name="console"),
    path("console/login/", c.login_view, name="console_login"),
    path("console/logout/", c.logout_view, name="console_logout"),
    path("console/leads/", c.leads, name="console_leads"),
    path("console/leads/<int:pk>/", c.lead_update, name="console_lead_update"),
    path("console/houses/", c.props, name="console_props"),
    path("console/houses/<int:pk>/", c.prop_action, name="console_prop_action"),
    path("console/announcements/", c.announcements, name="console_announcements"),
    path("console/announcements/<int:pk>/", c.announcement_action, name="console_announcement_action"),
    path("console/partners/", c.providers, name="console_providers"),
    path("console/partners/<int:pk>/", c.provider_action, name="console_provider_action"),
]
